# Stage 1: Build Stage
FROM golang:1.21.3 AS builder
WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o stresstest ./

# Stage 2: Production Stage
FROM scratch
WORKDIR /app
COPY --from=builder /app/stresstest .
ENTRYPOINT ["./stresstest"]