version: '3'

services:
  stresstest:
    image: stress-test
    container_name: stresstest
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile.prod}
    stdin_open: ${IS_DEV:-false}
    tty: ${IS_DEV:-false}

    ports:
      - "8080:8080"
